name: iniciar-implantacao-branche-main

on:
  pull_request:
    branches: ['main']
    types: ['closed']

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
